(function(){'use strict';var method;var noop=function(){};var methods=['assert','clear','count','debug','dir','dirxml','error','exception','group','groupCollapsed','groupEnd','info','log','markTimeline','profile','profileEnd','table','time','timeEnd','timeline','timelineEnd','timeStamp','trace','warn'];var length=methods.length;var console=(window.console=window.console||{});while(length--){method=methods[length];if(!console[method]){console[method]=noop;}}}());$(function(){'use strict';function detectIE(){var ua=window.navigator.userAgent;var msie=ua.indexOf('MSIE ');if(msie>0){return parseInt(ua.substring(msie+5,ua.indexOf('.',msie)),10);}
var trident=ua.indexOf('Trident/');if(trident>0){var rv=ua.indexOf('rv:');return parseInt(ua.substring(rv+3,ua.indexOf('.',rv)),10);}
var edge=ua.indexOf('Edge/');if(edge>0){return parseInt(ua.substring(edge+5,ua.indexOf('.',edge)),10);}
return false;}
var ie=detectIE();if(ie&&ie<=11){$("html").addClass("ie");}
var $navbar=$(".navigation"),stickyPoint=90;function navbarSticky(){if($(window).scrollTop()>=stickyPoint){$navbar.addClass("navbar-sticky");}else{$navbar.removeClass("navbar-sticky");}}
$(window).scroll(function(){navbarSticky();});navbarSticky();$('a.scrollto').on('click',function(event){event.preventDefault();var scrollAnimationTime=1200;var target=this.hash;$('html, body').stop().animate({scrollTop:$(target).offset().top},scrollAnimationTime,'easeInOutExpo',function(){window.location.hash=target;});});$(".navbar-toggler").on("click",function(){$navbar.toggleClass("navbar-expanded");});$(".tgl-signup").on('click',function(){$('body').toggleClass("signup-visible");$navbar.removeClass("navbar-expanded");});AOS.init({offset:200,duration:1500,disable:"mobile"});$('.swiper-container').each(function(){var $this=$(this);var breakPoints=false;var autoplay=$this.data('sw-autoplay')||2500;var speed=$this.data('sw-speed')||1100;var effect=$this.data('sw-effect')||"slide";var showItems=$this.data('sw-show-items')||1;var loop=$this.data('sw-loop')||true;var centered=$this.data('sw-centered-slides')||true;var spaceBetween=(showItems>1)?20:0;var scrollItems=$this.data('sw-scroll-items')||1;var navigationElement=$this.data('sw-navigation');var paginationElement=$this.data('sw-pagination')||'.swiper-pagination';var stretch=$this.data('sw-cover-stretch')||0;var depth=$this.data('sw-cover-depth')||0;var modifier=$this.data('sw-cover-modifier')||1;var pagination={pagination:{el:paginationElement,clickable:true,dynamicBullets:true},navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev'}};if(navigationElement){pagination.onTransitionEnd=function(sw){$('.active',navigationElement).removeClass('active');$('.nav-item:eq('+sw.realIndex+')',navigationElement).addClass('active');}}
var swOptions=$.extend({loop:loop,slidesPerGroup:scrollItems,spaceBetween:spaceBetween,centeredSlides:centered,breakpoints:breakPoints,slidesPerView:showItems,autoplay:{delay:autoplay,disableOnIteration:false},speed:speed,parallax:true,effect:effect,coverflow:{rotate:0,stretch:stretch,depth:depth,modifier:modifier,slideShadows:false}},pagination);var swiper=new Swiper(this,swOptions);if(navigationElement){$(navigationElement).on('click','.nav-item',function(evt){evt.preventDefault();var $item=$(this);if($item.hasClass('active')){return false;}
var index=$item.index();swiper.slideTo(index+1);$item.siblings('.active').removeClass('active');$item.addClass('active');return false;});}});if(document.getElementById("particles")){particlesJS.load('particles','js/particles/bubbles.json');}
if($(".typed").length){var typed=new Typed('.typed',{strings:['Easy','Shine','Great','Perfect'],typeSpeed:100,backDelay:600,backSpeed:50,loop:true});}});